default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: postgres
  host: postgres

development:
  <<: *default
  database: socianalyzr_development

test:
  <<: *default
  database: socianalyzr_test