#
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 10
#   username: postgres
#   host: postgres

# development:
#   <<: *default
#   database: gameoflife_development

# test:
#   <<: *default
#   database: gameoflife_test

default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  <<: *default
  database: gameoflife_development

test:
  <<: *default
  database: gameoflife_test
  username: postgres

